# Generated by Django 4.1 on 2023-11-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
