# Generated by Django 4.1 on 2022-11-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='original_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='selling_price',
            field=models.IntegerField(null=True),
        ),
    ]
