from django.urls import path
from . import views


urlpatterns = [
    path('',views.index,name='index'),
    path('admin_home',views.admin_home,name='admin_home'),
    path('user_details',views.user_details,name='user_details'),
    path('delete_user/<int:d>',views.delete_user,name='delete_user'),
    path('admin_logout',views.admin_logout,name='admin_logout'),
    path('block_action/<int:num>',views.block_user,name='block_action'),
    path('unblock_action/<int:val>',views.unblock_user,name='unblock_action'),
    path('account',views.accounts_admin,name='account'),
    path('add_products',views.add_products,name='add_products'),
    path('edit_products/<int:ed>',views.edit_products,name='edit_products'),
    path('add/ajax/load-subCats/', views.loadSubCats, name='ajax_load_subCats'),
    path('save_edited_products/<int:op>',views.save_edited_products,name='save_edited_products'),
    path('delete_products',views.delete_product,name='delete_products'),
    path('add_category',views.add_category1,name='add_category'),
    path('sub_category',views.sub_category1,name = 'sub_category'),
    path('delete_category',views.delete_category,name='delete_category'),
    path('edit_category/<int:va>',views.edit_category,name='edit_category'),
    path('save_edited_category/<int:va>',views.save_edited_category,name='save_edited_category'),
    path('save_sub/<int:i>',views.save_edit_sub,name='save_sub'),
    path('edit_sub/<int:u>/<int:ci>',views.edit_sub,name='edit_sub'),
    path('delete_sub',views.delete_sub,name='delete_sub'),
    path('products',views.products,name='products'),
    path('category',views.home_category,name='category'),
    path('order_management',views.order_details,name = 'order_management'),
    path('update_status',views.admin_updation,name='update_status'),
    path('add_coupen',views.add_coupens,name="add_coupen"),
    path('give',views.coupen_ajax, name='give'),
    path('coupenmanagement',views.coupen_home,name="coupenmanagement"),
    path('delete_coupen',views.delete_coupen,name="delete_coupen"),
    path('make_coupen',views.make_coupen,name="make_coupen"),
    path('offer',views.offer2,name="offer"),
    path('add_offer',views.add_offer,name="add_offer"),
    path('sum',views.offer_sum,name="sum"),
    path('save_offer',views.save_offer,name='save_offer'),
    path('delete_offer',views.delete_offer,name="delete_offer"),
    path('sales_report',views.sale,name="sales_report"),
    #path('get_date',views.filter_date,name="get_date"),
    path('Pdf',views.pd,name="Pdf"),
 ]
