# Generated by Django 4.1 on 2022-11-16 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='add_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='images/')),
                ('describtion', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='add_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('slug', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='images/')),
                ('imag2', models.ImageField(upload_to='images/')),
                ('image3', models.ImageField(upload_to='images/')),
                ('image4', models.ImageField(upload_to='images/')),
                ('describtion', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_price', models.CharField(max_length=50)),
                ('selling_price', models.CharField(max_length=50, null=True)),
                ('percentage', models.CharField(max_length=20, null=True)),
                ('features', models.TextField(max_length=700)),
                ('stock', models.CharField(max_length=1000)),
                ('offer_reduced_price', models.IntegerField(null=True)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondapp.add_category')),
            ],
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=80)),
                ('address', models.TextField(max_length=400)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='coupens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coup_name', models.CharField(max_length=100, unique=True)),
                ('discount', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('max_amount', models.IntegerField()),
                ('minimum_amount', models.IntegerField()),
                ('expired_at', models.IntegerField(null=True)),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='secondapp.add_category')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='secondapp.add_product')),
            ],
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondapp.add_category')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('order_status', models.CharField(default='pending', max_length=100)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.BigIntegerField()),
                ('complaint', models.TextField(max_length=1000, null=True)),
                ('coupen_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='secondapp.coupens')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondapp.add_product')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondapp.address')),
                ('us_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_percentage', models.IntegerField(null=True)),
                ('total_reduction', models.IntegerField(null=True)),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='secondapp.add_category')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='secondapp.add_product')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.BigIntegerField(null=True)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('ofer_reduced_price', models.IntegerField(null=True)),
                ('coupen_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='secondapp.coupens')),
                ('prd_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondapp.add_product')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='add_product',
            name='sub_category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondapp.sub_category'),
        ),
    ]
