# Generated by Django 4.1 on 2022-11-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_alter_add_product_original_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_product',
            name='cupen_reduced_price',
            field=models.IntegerField(null=True),
        ),
    ]
