# Generated by Django 4.1 on 2022-11-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0003_add_product_cupen_reduced_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_product',
            name='cupen_reduced_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='cupen_reduced_price',
            field=models.IntegerField(null=True),
        ),
    ]
