# Generated by Django 4.1 on 2023-11-09 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0005_alter_add_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupens',
            name='expired_at',
        ),
        migrations.AddField(
            model_name='coupens',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupens',
            name='is_experied',
            field=models.BooleanField(default=False),
        ),
    ]
